// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPZe0VEF84dKkKh46UJmlOCyb7-3YH5U4',
    appId: '1:364698561747:web:dad0641d9f886f149e7826',
    messagingSenderId: '364698561747',
    projectId: 'mehandi-new-studio',
    authDomain: 'mehandi-new-studio.firebaseapp.com',
    storageBucket: 'mehandi-new-studio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Ydj7tdwhXfKcTvQPFPu7rjPTJ8RIP4Y',
    appId: '1:364698561747:android:e45a09e61694c5359e7826',
    messagingSenderId: '364698561747',
    projectId: 'mehandi-new-studio',
    storageBucket: 'mehandi-new-studio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6_OPn933jRU0d681BAT7ajkqxrvmDxMg',
    appId: '1:364698561747:ios:32cbc969d8909a9a9e7826',
    messagingSenderId: '364698561747',
    projectId: 'mehandi-new-studio',
    storageBucket: 'mehandi-new-studio.firebasestorage.app',
    iosBundleId: 'com.example.mehendiBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6_OPn933jRU0d681BAT7ajkqxrvmDxMg',
    appId: '1:364698561747:ios:32cbc969d8909a9a9e7826',
    messagingSenderId: '364698561747',
    projectId: 'mehandi-new-studio',
    storageBucket: 'mehandi-new-studio.firebasestorage.app',
    iosBundleId: 'com.example.mehendiBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPZe0VEF84dKkKh46UJmlOCyb7-3YH5U4',
    appId: '1:364698561747:web:799b6a4660e75ac69e7826',
    messagingSenderId: '364698561747',
    projectId: 'mehandi-new-studio',
    authDomain: 'mehandi-new-studio.firebaseapp.com',
    storageBucket: 'mehandi-new-studio.firebasestorage.app',
  );
}
